import { TechCategory, TechItem } from '../pages/card-builder/TechCardBuilder';
import { 
  SiJavascript, SiTypescript, SiPython, SiSharp,
  SiCplusplus, SiRuby, SiGo, SiRust, SiSwift, SiKotlin, 
  SiPhp, SiC, SiScala, SiR, SiDart, SiElixir, SiHaskell, 
  SiLua, SiPerl, SiApple, SiGnubash, SiFsharp,
  SiClojure, SiReact, SiAngular, SiVuedotjs, SiNextdotjs, 
  SiNuxtdotjs, SiSvelte, SiDjango, SiFlask, SiSpring, 
  SiLaravel, SiExpress, SiDotnet, SiRubyonrails, SiFastapi, 
  SiNestjs, SiApachecordova, SiSymfony, SiFlutter, 
  SiXcode, SiPhoenixframework, 
  SiPlaycanvas, SiQuarkus, SiTensorflow, SiPytorch, 
  SiOpenai, SiHuggingface, SiChainlink, SiOpenbadges, 
  SiAirbnb, SiGoogle, 
  SiScikitlearn, SiKeras, SiPandas, SiNumpy, 
  SiJupyter, SiReverbnation, SiPinterest, 
  SiFastify, SiCodesandbox, 
  SiAlpinelinux, SiReplit, SiDatabricks, SiSnowflake, SiGithub, 
  SiDocker, SiKubernetes, SiAmazon, SiGooglecloud, 
  SiFigma, SiGraphql, 
  SiPostgresql, SiMongodb, SiRedis, SiMysql, SiSqlite, 
  SiNginx, SiApache, SiJenkins, SiGitlab, SiTerraform, 
  SiAnsible, SiPrometheus, SiGrafana, SiJira, SiSlack, SiPostman
} from 'react-icons/si';

import { 
  FaJava, FaNodeJs, FaReact, FaCode, FaTerminal,
  FaGlobe, FaBrain, FaDatabase, FaAws, FaMicrosoft,
  FaWindows, FaCode as FaVsCode
} from 'react-icons/fa';

import { IconType } from 'react-icons';

export const allTechnologies: { [key in TechCategory]: TechItem[] } = {
  languages: [
    { id: 'javascript', name: 'JavaScript', icon: SiJavascript, category: 'languages' },
    { id: 'typescript', name: 'TypeScript', icon: SiTypescript, category: 'languages' },
    { id: 'python', name: 'Python', icon: SiPython, category: 'languages' },
    { id: 'java', name: 'Java', icon: FaJava, category: 'languages' },
    { id: 'csharp', name: 'C#', icon: SiSharp, category: 'languages' },
    { id: 'cpp', name: 'C++', icon: SiCplusplus, category: 'languages' },
    { id: 'ruby', name: 'Ruby', icon: SiRuby, category: 'languages' },
    { id: 'golang', name: 'Go', icon: SiGo, category: 'languages' },
    { id: 'rust', name: 'Rust', icon: SiRust, category: 'languages' },
    { id: 'swift', name: 'Swift', icon: SiSwift, category: 'languages' },
    { id: 'kotlin', name: 'Kotlin', icon: SiKotlin, category: 'languages' },
    { id: 'php', name: 'PHP', icon: SiPhp, category: 'languages' },
    { id: 'c', name: 'C', icon: SiC, category: 'languages' },
    { id: 'scala', name: 'Scala', icon: SiScala, category: 'languages' },
    { id: 'r', name: 'R', icon: SiR, category: 'languages' },
    { id: 'dart', name: 'Dart', icon: SiDart, category: 'languages' },
    { id: 'elixir', name: 'Elixir', icon: SiElixir, category: 'languages' },
    { id: 'haskell', name: 'Haskell', icon: SiHaskell, category: 'languages' },
    { id: 'lua', name: 'Lua', icon: SiLua, category: 'languages' },
    { id: 'perl', name: 'Perl', icon: SiPerl, category: 'languages' },
    { id: 'objective-c', name: 'Objective-C', icon: SiApple, category: 'languages' },
    { id: 'groovy', name: 'Groovy', icon: SiGnubash, category: 'languages' },
    { id: 'fsharp', name: 'F#', icon: SiFsharp, category: 'languages' },
    { id: 'assembly', name: 'Assembly', icon: FaTerminal, category: 'languages' },
    { id: 'clojure', name: 'Clojure', icon: SiClojure, category: 'languages' },
  ],
  frameworks: [
    { id: 'react', name: 'React', icon: FaReact, category: 'frameworks' },
    { id: 'angular', name: 'Angular', icon: SiAngular, category: 'frameworks' },
    { id: 'vue', name: 'Vue', icon: SiVuedotjs, category: 'frameworks' },
    { id: 'nextjs', name: 'Next.js', icon: SiNextdotjs, category: 'frameworks' },
    { id: 'nuxtjs', name: 'Nuxt.js', icon: SiNuxtdotjs, category: 'frameworks' },
    { id: 'svelte', name: 'Svelte', icon: SiSvelte, category: 'frameworks' },
    { id: 'django', name: 'Django', icon: SiDjango, category: 'frameworks' },
    { id: 'flask', name: 'Flask', icon: SiFlask, category: 'frameworks' },
    { id: 'spring', name: 'Spring Boot', icon: SiSpring, category: 'frameworks' },
    { id: 'laravel', name: 'Laravel', icon: SiLaravel, category: 'frameworks' },
    { id: 'express', name: 'Express.js', icon: SiExpress, category: 'frameworks' },
    { id: 'dotnet', name: '.NET', icon: SiDotnet, category: 'frameworks' },
    { id: 'rubyonrails', name: 'Ruby on Rails', icon: SiRubyonrails, category: 'frameworks' },
    { id: 'fastapi', name: 'FastAPI', icon: SiFastapi, category: 'frameworks' },
    { id: 'nestjs', name: 'NestJS', icon: SiNestjs, category: 'frameworks' },
    { id: 'emberjs', name: 'Ember.js', icon: SiApachecordova, category: 'frameworks' },
    { id: 'symfony', name: 'Symfony', icon: SiSymfony, category: 'frameworks' },
    { id: 'aspnet', name: 'ASP.NET Core', icon: SiDotnet, category: 'frameworks' },
    { id: 'flutter', name: 'Flutter', icon: SiFlutter, category: 'frameworks' },
    { id: 'reactnative', name: 'React Native', icon: FaReact, category: 'frameworks' },
    { id: 'xamarin', name: 'Xamarin', icon: SiXcode, category: 'frameworks' },
    { id: 'phoenix', name: 'Phoenix', icon: SiPhoenixframework, category: 'frameworks' },
    { id: 'gin', name: 'Gin', icon: FaGlobe, category: 'frameworks' },
    { id: 'playframework', name: 'Play Framework', icon: SiPlaycanvas, category: 'frameworks' },
    { id: 'quarkus', name: 'Quarkus', icon: SiQuarkus, category: 'frameworks' },
  ],
  ai: [
    { id: 'tensorflow', name: 'TensorFlow', icon: SiTensorflow, category: 'ai' },
    { id: 'pytorch', name: 'PyTorch', icon: SiPytorch, category: 'ai' },
    { id: 'openai', name: 'OpenAI API', icon: SiOpenai, category: 'ai' },
    { id: 'huggingface', name: 'Hugging Face', icon: SiHuggingface, category: 'ai' },
    { id: 'langchain', name: 'LangChain', icon: SiChainlink, category: 'ai' },
    { id: 'llamaindex', name: 'LlamaIndex', icon: FaDatabase, category: 'ai' },
    { id: 'chatgpt', name: 'ChatGPT', icon: SiOpenbadges, category: 'ai' },
    { id: 'dall-e', name: 'DALL-E', icon: SiOpenai, category: 'ai' },
    { id: 'stable-diffusion', name: 'Stable Diffusion', icon: FaGlobe, category: 'ai' },
    { id: 'claude', name: 'Anthropic Claude', icon: SiAirbnb, category: 'ai' },
    { id: 'gemini', name: 'Google Gemini', icon: SiGoogle, category: 'ai' },
    { id: 'mistral', name: 'Mistral AI', icon: FaBrain, category: 'ai' },
    { id: 'scikit-learn', name: 'Scikit-learn', icon: SiScikitlearn, category: 'ai' },
    { id: 'keras', name: 'Keras', icon: SiKeras, category: 'ai' },
    { id: 'pandas', name: 'Pandas', icon: SiPandas, category: 'ai' },
    { id: 'numpy', name: 'NumPy', icon: SiNumpy, category: 'ai' },
    { id: 'jupyter', name: 'Jupyter', icon: SiJupyter, category: 'ai' },
    { id: 'weaviate', name: 'Weaviate', icon: SiReverbnation, category: 'ai' },
    { id: 'pinecone', name: 'Pinecone', icon: SiPinterest, category: 'ai' },
    { id: 'fastai', name: 'fast.ai', icon: SiFastify, category: 'ai' },
    { id: 'cohere', name: 'Cohere', icon: SiCodesandbox, category: 'ai' },
    { id: 'alephalpha', name: 'Aleph Alpha', icon: SiAlpinelinux, category: 'ai' },
    { id: 'replicate', name: 'Replicate', icon: SiReplit, category: 'ai' },
    { id: 'databricks', name: 'Databricks', icon: SiDatabricks, category: 'ai' },
    { id: 'snowflake', name: 'Snowflake', icon: SiSnowflake, category: 'ai' },
  ],
  tools: [
    { id: 'github', name: 'GitHub', icon: SiGithub, category: 'tools' },
    { id: 'docker', name: 'Docker', icon: SiDocker, category: 'tools' },
    { id: 'kubernetes', name: 'Kubernetes', icon: SiKubernetes, category: 'tools' },
    { id: 'aws', name: 'AWS', icon: FaAws, category: 'tools' },
    { id: 'gcp', name: 'Google Cloud', icon: SiGooglecloud, category: 'tools' },
    { id: 'azure', name: 'Azure', icon: FaMicrosoft, category: 'tools' },
    { id: 'figma', name: 'Figma', icon: SiFigma, category: 'tools' },
    { id: 'vscode', name: 'VS Code', icon: FaVsCode, category: 'tools' },
    { id: 'graphql', name: 'GraphQL', icon: SiGraphql, category: 'tools' },
    { id: 'postgresql', name: 'PostgreSQL', icon: SiPostgresql, category: 'tools' },
    { id: 'mongodb', name: 'MongoDB', icon: SiMongodb, category: 'tools' },
    { id: 'redis', name: 'Redis', icon: SiRedis, category: 'tools' },
    { id: 'mysql', name: 'MySQL', icon: SiMysql, category: 'tools' },
    { id: 'sqlite', name: 'SQLite', icon: SiSqlite, category: 'tools' },
    { id: 'nginx', name: 'Nginx', icon: SiNginx, category: 'tools' },
    { id: 'apache', name: 'Apache HTTP', icon: SiApache, category: 'tools' },
    { id: 'jenkins', name: 'Jenkins', icon: SiJenkins, category: 'tools' },
    { id: 'gitlab', name: 'GitLab', icon: SiGitlab, category: 'tools' },
    { id: 'terraform', name: 'Terraform', icon: SiTerraform, category: 'tools' },
    { id: 'ansible', name: 'Ansible', icon: SiAnsible, category: 'tools' },
    { id: 'prometheus', name: 'Prometheus', icon: SiPrometheus, category: 'tools' },
    { id: 'grafana', name: 'Grafana', icon: SiGrafana, category: 'tools' },
    { id: 'jira', name: 'Jira', icon: SiJira, category: 'tools' },
    { id: 'slack', name: 'Slack', icon: SiSlack, category: 'tools' },
    { id: 'postman', name: 'Postman', icon: SiPostman, category: 'tools' },
  ],
}; 