<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - Shreyas's Portfolio</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            background-color: #f3f4f6;
            padding: 0;
            margin: 0;
          }
          .header {
            background: linear-gradient(to right, #38BDF8, #818CF8, #A855F7);
            color: white;
            padding: 2rem;
            text-align: center;
          }
          h1 {
            margin: 0;
            font-size: 24px;
            font-weight: 700;
          }
          .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
          }
          .info {
            background-color: #fff;
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 2rem;
            box-shadow: 0 2px 15px rgba(0, 0, 0, 0.05);
          }
          table {
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 15px rgba(0, 0, 0, 0.05);
            overflow: hidden;
          }
          th {
            background-color: #f3f4f6;
            padding: 1rem;
            text-align: left;
            font-weight: 600;
            color: #374151;
            text-transform: uppercase;
            font-size: 14px;
            letter-spacing: 0.05em;
          }
          td {
            padding: 1rem;
            border-top: 1px solid #e5e7eb;
            font-size: 14px;
            color: #4b5563;
          }
          a {
            color: #2563eb;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          .url-cell {
            word-break: break-all;
          }
          .priority-high {
            color: #059669;
          }
          .priority-medium {
            color: #0284c7;
          }
          .priority-low {
            color: #6366f1;
          }
          .footer {
            margin-top: 2rem;
            text-align: center;
            font-size: 14px;
            color: #6b7280;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Shreyas's Portfolio XML Sitemap</h1>
        </div>
        <div class="container">
          <div class="info">
            <p>This is an XML Sitemap generated for better search engine visibility. Learn more about <a href="https://www.sitemaps.org/" target="_blank">XML Sitemaps</a>.</p>
            <p>This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
          </div>
          <table>
            <tr>
              <th>URL</th>
              <th>Priority</th>
              <th>Change Frequency</th>
              <th>Last Modified</th>
            </tr>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td class="url-cell">
                  <a href="{sitemap:loc}">
                    <xsl:value-of select="sitemap:loc"/>
                  </a>
                </td>
                <td>
                  <xsl:variable name="priority" select="sitemap:priority"/>
                  <xsl:choose>
                    <xsl:when test="$priority &gt;= 0.9">
                      <span class="priority-high"><xsl:value-of select="$priority"/></span>
                    </xsl:when>
                    <xsl:when test="$priority &gt;= 0.7">
                      <span class="priority-medium"><xsl:value-of select="$priority"/></span>
                    </xsl:when>
                    <xsl:otherwise>
                      <span class="priority-low"><xsl:value-of select="$priority"/></span>
                    </xsl:otherwise>
                  </xsl:choose>
                </td>
                <td><xsl:value-of select="sitemap:changefreq"/></td>
                <td><xsl:value-of select="sitemap:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </table>
          <div class="footer">
            <p>Generated by Shreyas's Portfolio | <xsl:value-of select="format-date(current-date(), '[Y]-[M01]-[D01]')"/></p>
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet> 